env:
  global:
    # DOCKER_USER
    - secure: "TTeNny1KCr7qDqKyhHr1HJ0CQAHaVwavo7ZnSs7jE2mPX6T3ISOJDO+ItTvG2dZMHzE9aih6UgulTx08y97tnESakdjWUnCUlUi1mwbnODL7GmJQllSOcvRbA3Hm9N/3tFQJV/APz1ZUfiGSpfwSUza5DBe5avpO3/1RFZiSexHubms1BIxE+MCyUxFp/rGIGhRS2MfFYBRxlKX4Xo87fHlMbopO2v5ewM8Iyv4z0Cj2GC8u4UMJO946H/AXp1rdP3B+GLRolgn6ECaBH+t5IuD/nbtyawSGnNesNd68Wk83y7KPJobyY6JmxBaksWxxvTacgQeF6jADf7Jc18hPTUgHsHkKf2NwGGkP+b8UD4rRf/icIQ06x34GXRpCBc5/JNrab1n0zh6VvdjOnFIuA4E8crqPDhhrQSVsWL7X+Sufa1exuvbDhXKzKV8ss+ShXUrRJyHnlyIA0nJj0KcI+UleilTfP/05rYwCyu54U/HH55AOHsTlPrZm9hMuy1d0h2S+Zs9CqmSblwGaYDlrCiEc5+Ov51jIRCaqxuazgRrPgrJA4jE4ope8Q4G62vHN2g9PB+KsY7u4OYXN3JnPW1Vlf05Nc4KYpwTD5NINGx2z1G0tE/VErziesiVOu5GhTepos6l8Z7JARqfiXPHX5+lGdE0qTK3n1axfa9GCQkQ="
    # DOCKER_PASS
    - secure: "ALVKNERRaARCQdQhvzH/RteMlu+TCgEkp+/KWcrRu3J7ID0M4fCThbc6fvZAsD0pNkCHv6g/8qbGVl6IakH5j+m0LbG7+xozF2W+AZphtd8HcDxevqTOAka5fbd13PA/wJgW7getSJSlLo6OSPIwo1AHeEvDYjx37CtGZepiUdl4b9dwB06WtzEPKgMBiCsASj99xeOI2j92e71NdOeJdO8n9CbSHFjwZ+ZX/RKaqex1Bl2UEadUUX6GmOjvks0pqEMvJo7bfsaXLzu8ZAGxcbQ1S8XfaXbWGJvfZQEa+OyLU7dFd/3V3Q2gOGodQfd4RKccSIOCu0CVw+r0clUay/BF+zIPcZK88+PftY5VyPXRx0EXPWoFRq6NihOvG9+3FOHAXpMw0rHcgsGQKsbmQJSFKf7AFRej3qpzP7G26b/9C5WjOUoWP6EA+0I1Y4rMfYEQV53QbsJihlqGf6mQv7oy27ZTdPUFvEWTuTX7U9n6PH7X37mzxqFQkBYsj2nUhHYgIj9W/p0MvDAnsovk8L04vmLxC65iS5V5FCIFrz/sXNQw9yKx8u+e2YJ+M2BsRYhYBixFeexVubMMXds1dxbY3zUgTsTU1m4KonvhZuQVN2DLxXrgo59cZoUkWMSPERUI5xZtw+6VAMTzj8O006B4GzUbo7UIhVLjh82xFrE="
    # Where to push the Docker image
    - DOCKER_REPO=comfy/pypicloud
services:
  - docker
before_script:
  # Log in to docker hub
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  # Get tags for this build
  - DOCKER_TAGS=$(sh get-docker-tags.sh $DOCKER_REPO)
script:
  # Build and tag the docker image
  - docker build -t current $DOCKER_TAGS .
after_success:
  # Show built images
  - docker images
  # If we tagged this image, push it to Docker Hub
  - test ! -z "$DOCKER_TAGS" && docker push $DOCKER_REPO
