env:
  global:
    - DOCKER_REPO=comfy/pypicloud
services:
  - docker
cache:
  directories:
    - ~/docker
before_script:
  # Log in to docker hub
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  # Get tags for this build
  - DOCKER_TAGS=$(sh get-docker-tags.sh $DOCKER_REPO)
  - if [[ -e ~/docker ]]; then ls -l ~/docker; fi
  # Load image from cache so layers can be reused
  - if [[ -e ~/docker/image.tar ]]; then docker load -i ~/docker/image.tar; fi
  - docker images
script:
  # Build and tag the sMAP docker image
  - docker build -t current $DOCKER_TAGS .
  # Export the image to the cached directory
  - mkdir -p ~/docker; docker save -o ~/docker/image.tar current $DOCKER_REPO
  - ls -l ~/docker
after_success:
  # Show built images
  - docker images
  # If we tagged this image, push it to Docker Hub
  - test ! -z "$DOCKER_TAGS" && docker push $DOCKER_REPO
