env:
  global:
    - DOCKER_REPO=comfy/pypicloud
services:
  - docker
before_script:
  # Log in to docker hub
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  # Pull docker image so we can reuse layers in the build step
  - docker pull $DOCKER_REPO
script:
  # Get tags for this build
  - DOCKER_TAGS=$(./get-docker-tags.sh $DOCKER_REPO)
  # Build and tag the sMAP docker image
  - docker build -t current $DOCKER_TAGS .
after_success:
  # If we tagged this image, push it to Docker Hub
  - test ! -z $DOCKER_TAGS && docker push $DOCKER_REPO
